# .github/workflows/build-and-deploy.yml
name: Build and Deploy Markdown to HTML with Custom CSS and Title Formatting

on:
  push:
    branches:
      - main  # Triggers the workflow on push to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # Uses the latest Ubuntu runner

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false  # Ensures GITHUB_TOKEN is not persisted
          fetch-depth: 0  # Fetches all history for all branches and tags

      # Step 2: Install Pandoc
      - name: Install Pandoc
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc

      # Step 3: Install LaTeX packages (Optional)
      - name: Install LaTeX Packages
        run: |
          sudo apt-get install -y texlive-latex-extra

      # Step 4: Prepare Public Directory and Assets
      - name: Prepare Public Directory
        run: |
          mkdir -p public
          
          # Copy CSS files to the public directory
          cp -r styles public/styles
          
          # Copy images and other assets if they exist
          # Uncomment and modify the following lines if needed:
          # cp -r src/images public/images
          
          # Copy custom template to public/ (if necessary)
          # If the template is used via relative path, no need to copy
          # cp templates/custom-template.html public/templates/custom-template.html

      # Step 5: Convert Markdown to HTML Using Custom Template and Replace Hyphens
      - name: Convert Markdown to HTML
        run: |
          # Find all Markdown files in src/ and convert them
          find src -name "*.md" | while read md; do
            # Define the output HTML path by replacing 'src/' with 'public/' and changing extension to .html
            html="public/${md#src/}"
            html="${html%.md}.html"
            
            # Create necessary directories in public/
            mkdir -p "$(dirname "$html")"
            
            # Extract the base filename without extension
            base_name="$(basename "$md" .md)"
            
            # Replace hyphens with spaces in the title
            formatted_title="${base_name//-/ }"
            
            # Convert Markdown to HTML with standalone flag, custom template, and link CSS
            pandoc "$md" -o "$html" -s --template=templates/custom-template.html -c styles/main.css --metadata title="$formatted_title"
          done

      # Step 6: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public  # Directory to publish
          # For user/organization sites, no need to specify the branch
          # It defaults to the repository's GitHub Pages settings