# .github/workflows/build-and-deploy.yml
name: Build and Deploy Markdown to HTML with CSS

on:
  push:
    branches:
      - main  # Triggers the workflow on push to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # Uses the latest Ubuntu runner

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false  # Ensures GITHUB_TOKEN is not persisted
          fetch-depth: 0  # Fetches all history for all branches and tags

      # Step 2: Install Pandoc
      - name: Install Pandoc
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc

      # Step 3: Install LaTeX packages (Optional)
      # Install LaTeX packages if your Markdown uses LaTeX
      - name: Install LaTeX Packages
        run: |
          sudo apt-get install -y texlive-latex-extra

      # Step 4: Prepare Public Directory and Assets
      - name: Prepare Public Directory
        run: |
          mkdir -p public
          
          # Copy CSS files to the public directory
          cp -r styles public/styles
          
          # If you have images or other assets, copy them here
          # Uncomment and modify the following line if needed:
          # cp -r src/images public/images

      # Step 5: Convert Markdown to HTML
      - name: Convert Markdown to HTML
        run: |
          # Find all Markdown files in src/ and convert them
          find src -name "*.md" | while read md; do
            # Define the output HTML path by replacing 'src/' with 'public/' and changing extension to .html
            html="public/${md#src/}"
            html="${html%.md}.html"
            
            # Create necessary directories in public/
            mkdir -p "$(dirname "$html")"
            
            # Convert Markdown to HTML with standalone flag and link CSS
            pandoc "$md" -o "$html" -s -c styles/main.css --metadata title="$(basename "$md" .md)"
          done

      # Step 6: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public  # Directory to publish
          # For user/organization sites (username.github.io), no need to specify the branch
          # It defaults to the repository's GitHub Pages settings